### ISSUE TITLE
Google sign in on android doesnt seem to work

### ISSUE THREAD

**Issue by Afsal102** [tadaspetra/conveneapp#109]
Some reports were indicating that the google sign in in android doesn't seem to work.

**Comment by Afsal102** [comment]
After some research: found out that we have to fill all the required info in the google sigin consent(available in the cloud console) cc: @tadaspetra

**Comment by tadaspetra** [comment]
Is it working now? If so we can close this :)

**Comment by Afsal102** [comment]
yep! closing!
