### ISSUE TITLE
Share review to Twitter

### ISSUE THREAD

**Issue by tadaspetra** [tadaspetra/conveneapp#19]
**Describe the feature you'd like to see**
After you finish your review add a way to share that review to Twitter

**Additional context**
Might have to be broken up into a thread

**Comment by HaardikBhagtani** [comment]
[`flutter_share_me: ^1.2.0`](https://pub.dev/packages/flutter_share_me) 
I haven't used this plugin yet. 
But you can use try plugin to share any message or review on Twitter or any other social media.
