### ISSUE TITLE
Handle error while retrieving the user's current books

### ISSUE THREAD

**Issue by varunbhalerao56** [tadaspetra/conveneapp#37]
Currently, there is no error handling implemented in the app.

This was created after making changes in #36.

When retrieving the books data of the current user from firebase there is no error handling, this issue is to address this all over the app and not only in this specific case.

Solutions:
 - Wrap in try and catch block and throw an error and handle it where it is called.
 - Pass context into the method to show a snack bar with the error message.

**Comment by Afsal102** [comment]
@tadaspetra @varunbhalerao56  this is fixed aint it? should be closed!
