### ISSUE TITLE
Add package `go_router` as the navigation method

### ISSUE THREAD

**Issue by tadaspetra** [tadaspetra/conveneapp#73]
**Is your proposal related to a problem? Please describe.** 
The current app is using some basic Navigator 1.0, which is fine, but longer term we should use Navigator 2.0 to keep things well organized, and `go_router` looks like the most promising package, as it's developed by a flutter employee.

**Describe alternatives you've considered** 
Some other packages that seem to be very quality like `routemaster`

**Comment by Afsal102** [comment]
@tadaspetra +1 `go_router` => this is well maintained(will be too in my pov).

**Comment by tadaspetra** [comment]
@Afsal102 i am leaning towards that one as well, but I thought it would be good to explore the Riverpod one as it's maintained by someone I know to be reliable. It is a really new package though so go_router might be better either way

**Comment by Afsal102** [comment]
> @Afsal102 i am leaning towards that one as well, but I thought it would be good to explore the Riverpod one as it's maintained by someone I know to be reliable. It is a really new package though so go_router might be better either way


that package was last update on june ? if its reliable then we might use it

**Comment by tadaspetra** [comment]
> > @Afsal102 i am leaning towards that one as well, but I thought it would be good to explore the Riverpod one as it's maintained by someone I know to be reliable. It is a really new package though so go_router might be better either way
> 
> that package was last update on june ? if its reliable then we might use it

Damn June is quite a while ago, I think it's better to go with go_router then

**Comment by Afsal102** [comment]
> > > @Afsal102 i am leaning towards that one as well, but I thought it would be good to explore the Riverpod one as it's maintained by someone I know to be reliable. It is a really new package though so go_router might be better either way
> > 
> > 
> > that package was last update on june ? if its reliable then we might use it
> 
> Damn June is quite a while ago, I think it's better to go with go_router then

Great ! though i am not sure if mocking `go_router` is easy? without injecting it to the constructor

**Comment by Afsal102** [comment]
@tadaspetra  i will try to do a sample and check how easy will this be to test !

**Comment by Afsal102** [comment]
@tadaspetra  have u tried `flow_builder` by vgv (i personally use it), not sure if u have heard / tried it?

**Comment by tadaspetra** [comment]
@Afsal102 I haven't tried it, but I have heard good things about it. I think I'd prefer go_router though, just because it's Chris Sells that made it

**Comment by Afsal102** [comment]
> @Afsal102 I haven't tried it, but I have heard good things about it. I think I'd prefer go_router though, just because it's Chris Sells that made it

Ok

**Comment by tadaspetra** [comment]
I don't think we need this, at least not yet
