### ISSUE TITLE
Refactor book_api

### ISSUE THREAD

**Issue by Afsal102** [tadaspetra/conveneapp#80]
**Is your proposal related to a problem? Please describe.** 
Current implementation calls `getCurrentBooks` after each transaction. So you will be billed for all the requests every time

 ```dart
 Future<void> addBook({required SearchBookModel book}) async {
    try {
      await BookApi().addBook(book: book, uid: uid);
	// ! will be billed for all the request every time
      final List<BookModel> books = await BookApi().getCurrentBooks(uid: uid);
      state = AsyncData(books);
    } catch (e, st) {
      throw AsyncError<Exception>(e, stackTrace: st);
    }
  }

  Future<void> updateBook({required BookModel book}) async {
    try {
      await BookApi().updateBook(book: book, uid: uid);
      // ! will be billed for all the request every time
      final List<BookModel> books = await BookApi().getCurrentBooks(uid: uid);
      state = AsyncData(books);
    } catch (e, st) {
      throw AsyncError<Exception>(e, stackTrace: st);
    }
  }
```
**Describe the solution you'd like** 
Create a stream to listen `currentBooks`, so this way we will be only billed for the new data which changed. 
ie : initial 20 data
incoming new data set with initial + changed data => we will only be billed for the changed data

**Comment by Afsal102** [comment]
@tadaspetra  initialise cloud functions directory to write needed functions in book's api
```dart
Future<void> finishBook({required BookModel book, required String uid}) async {
    await users.doc(uid).collection("currentBooks").doc(book.id).delete();
	// - should be executed by cloud function when the book is deleted, this way reduce the load in the front end
    await users
        .doc(uid)
        .collection("finishedBooks")
        .add(book.copyWith(dateCompleted: DateTime.now(), currentPage: book.pageCount).toMap());
  }
  ```
@tadaspetra write a cloud function when a book is deleted in the `currentBooks` get the deleted data and write it to `finishedBooks`

**Comment by tadaspetra** [comment]
> @tadaspetra initialise cloud functions directory to write needed functions in book's api
> 
> ```dart
> Future<void> finishBook({required BookModel book, required String uid}) async {
>     await users.doc(uid).collection("currentBooks").doc(book.id).delete();
> 	// - should be executed by cloud function when the book is deleted, this way reduce the load in the front end
>     await users
>         .doc(uid)
>         .collection("finishedBooks")
>         .add(book.copyWith(dateCompleted: DateTime.now(), currentPage: book.pageCount).toMap());
>   }
> ```
> 
> @tadaspetra write a cloud function when a book is deleted in the `currentBooks` get the deleted data and write it to `finishedBooks`

You're saying when we delete the data from current books to write to finishedBooks based on that trigger? I don't think that's a good one because it could also be deleted using a different option than finishBook
