### ISSUE TITLE
Current books don't load in

### ISSUE THREAD

**Issue by tadaspetra** [tadaspetra/conveneapp#92]
**Describe the bug**
If there is no book, you get the message 'Looks like you aren’t reading any books currently', but when you have some books in the current book list it doesn't update the view, and if you restart the app it just shows `CircularProgressIndicator()` forever!!!

![image](https://user-images.githubusercontent.com/60107328/144064578-4cafc124-5247-43b0-a713-797a018a6675.png)

**To Reproduce**
What device did you use?
1. Add a book to current book list
2. It doesn't show up in the main screen
3. Refresh the app
4. It stays in `CircularProgressIndicator()` forever

**Expected behavior**
To see the current books

**Comment by Afsal102** [comment]
@tadaspetra  merge #82 works fine!,
Bugs were in the book_model 
	>- `currentPage: map['currentPage']`
 	>+`currentPage: map['currentPage'] ?? 0,`

 The data in firestore doesnt have a field called `currentPage`  when the book is added so this is causing the issue !

 -  if u enable `allExceptions` in ur vscode debugging console u can see it 
 
> Fixes
 - Issues in the book_card
 - Book models should be properly tested!
